name: Documentation
description: Report any mistakes or missing information from the documentation or the examples
labels: kind/documentation
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Link to the issue (please include a link to the specific documentation or example).
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
